### ISSUE TITLE
Error with .NET 6

### ISSUE THREAD

**Issue by Taelyn** [ffMathy/FluffySpoon.AspNet.EncryptWeMust#226]
System.MissingMethodException: Method not found: 'Void Certes.AcmeContext..ctor(System.Uri, Certes.IKey, Certes.Acme.IAcmeHttpClient)'.
   at FluffySpoon.AspNet.EncryptWeMust.Certes.LetsEncryptClientFactory.GetContext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at FluffySpoon.AspNet.EncryptWeMust.Certes.LetsEncryptClientFactory.GetContext()
   at FluffySpoon.AspNet.EncryptWeMust.Certes.LetsEncryptClientFactory.GetClient()
   at FluffySpoon.AspNet.EncryptWeMust.Certificates.CertificateProvider.RequestNewLetsEncryptCertificate()
   at FluffySpoon.AspNet.EncryptWeMust.Certificates.CertificateProvider.RenewCertificateIfNeeded(IAbstractCertificate current)
   at FluffySpoon.AspNet.EncryptWeMust.Certes.LetsEncryptRenewalService.RunOnceAsync()
   at FluffySpoon.AspNet.EncryptWeMust.Certes.LetsEncryptRenewalService.RunOnceAsync()
   at FluffySpoon.AspNet.EncryptWeMust.Certes.LetsEncryptRenewalService.RunOnceWithErrorHandlingAsync()

**Comment by Klivess** [comment]
Did you find a fix for this? I'm trying to fix it myself.

**Comment by Taelyn** [comment]
I downloaded the source, updated all packages and recompliled it my self

That fixed it for me

**Comment by ffMathy** [comment]
Could you make a PR for it so it could benefit others too?
